from __future__ import annotations

from typing import TYPE_CHECKING, Any

from yatracker.tracker.base import BaseTracker, _encode_key
from yatracker.types.gap import Gap, GapsResult, GapsSearchResult, UserGaps
from yatracker.utils.datetime import to_tracker_datetime

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Mapping, Sequence
    from datetime import datetime

# ruff: noqa: PLR0913

#: The API rejects a request carrying more absence records than this.
MAX_GAPS_PER_REQUEST = 100


def _encode_gap(gap: Mapping[str, Any]) -> dict[str, Any]:
    """Bring one absence record to the request format.

    Keys are camel-cased like payload keys (`full_day` -> `fullDay`,
    `from_` -> `from`), `None` values are dropped and the `from` / `to`
    moments accept a `datetime` as well as a ready-made API string.
    """
    encoded = {
        _encode_key(key): value for key, value in gap.items() if value is not None
    }
    for key in ("from", "to"):
        if key in encoded:
            encoded[key] = to_tracker_datetime(encoded[key], stacklevel=4)
    return encoded


class Gaps(BaseTracker):
    """Absence records of employees (vacations, sick leaves, duties, ...).

    Absences are shown on user avatars and on the resource chart of
    portfolios and projects. Every request of this category requires
    organization admin rights.
    """

    async def create_gap(
        self,
        user: str | int,
        workflow: str,
        from_: datetime | str,
        to: datetime | str,
        *,
        gap_id: str | None = None,
        full_day: bool | None = None,
        work_in_absence: bool | None = None,
    ) -> Gap:
        """Create one absence record.

        Use :meth:`create_gaps` to send up to 100 records at once.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/post-gaps

        :param user: login or id of the employee.
        :param workflow: absence type: "vacation", "paid_day_off",
            "illness", "absence", "trip", "conference_trip",
            "conference", "learning", "maternity" or "duty". The
            up-to-date list is served by `GET /v3/gaps/workflows`.
        :param from_: start of the absence, a datetime or an API string.
            Must be less than `to`.
        :param to: end of the absence, a datetime or an API string.
        :param gap_id: id to assign to the record (sent as `id`), at
            most 128 characters. Generated by the API when omitted.
        :param full_day: whether the absence takes the whole day
            (`False` by default).
        :param work_in_absence: whether the employee works during the
            absence (`False` by default).
        :return: created absence record.
        :raises ValueError: if the API saved no record.
        """
        gap: dict[str, Any] = {
            "id": gap_id,
            "user": user,
            "workflow": workflow,
            "from": to_tracker_datetime(from_),
            "to": to_tracker_datetime(to),
            "fullDay": full_day,
            "workInAbsence": work_in_absence,
        }
        gaps = await self.create_gaps([gap])
        if not gaps:
            msg = "The API saved no absence record for this request."
            raise ValueError(msg)
        return gaps[0]

    async def create_gaps(
        self,
        gaps: Sequence[Mapping[str, Any]],
    ) -> list[Gap]:
        """Create several absence records at once.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/post-gaps

        :param gaps: absence records to create, at most 100. Every
            record is a mapping with the `user`, `workflow`, `from_`
            (or `from`) and `to` keys and the optional `id`, `full_day`
            and `work_in_absence` ones; keys are camel-cased and the
            moments accept a `datetime`.
        :return: records that were actually saved (outdated ones are
            not returned by the API).
        """
        if len(gaps) > MAX_GAPS_PER_REQUEST:
            msg = (
                f"At most {MAX_GAPS_PER_REQUEST} absence records can be "
                f"created at once, got {len(gaps)}."
            )
            raise ValueError(msg)

        # a plain loop, not a comprehension: on Python < 3.12 a comprehension
        # adds a frame and the naive-datetime warning would point at this
        # module instead of the caller (PEP 709 removed that frame later)
        encoded: list[dict[str, Any]] = []
        for gap in gaps:
            encoded.append(_encode_gap(gap))  # noqa: PERF401
        data = await self._client.request(
            method="POST",
            uri="/gaps",
            payload={"gaps": encoded},
        )
        return self._decode(GapsResult, data).gaps

    async def search_gaps(
        self,
        users: Sequence[str | int],
        *,
        from_: datetime | str | None = None,
        to: datetime | str | None = None,
        per_page: int | None = None,
        page: int | None = None,
    ) -> GapsSearchResult:
        """Find the absence records of the given employees.

        The records returned are the ones overlapping the time window;
        the result is grouped by employee and holds one entry for every
        requested employee, with an empty `gaps` list when there is no
        match.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/search-gaps

        :param users: logins or ids of the employees, at most 100.
        :param from_: start of the search window, a datetime or an API
            string. The current moment by default.
        :param to: end of the search window, a datetime or an API
            string. Must be strictly greater than `from_`.
        :param per_page: number of employees per page (50 by default).
        :param page: page number (1 by default).
        :return: page of absence records grouped by employee.
        """
        from_ = to_tracker_datetime(from_)
        to = to_tracker_datetime(to)

        payload = self._prepare_payload(
            locals(),
            exclude=["per_page", "page"],
        )
        payload["users"] = [str(user) for user in users]

        params = self._prepare_params(per_page=per_page, page=page)
        data = await self._client.request(
            method="POST",
            uri="/gaps/_search",
            params=params,
            payload=payload,
        )
        return self._decode(GapsSearchResult, data)

    async def iter_gaps(
        self,
        users: Sequence[str | int],
        *,
        from_: datetime | str | None = None,
        to: datetime | str | None = None,
        per_page: int | None = None,
    ) -> AsyncIterator[UserGaps]:
        """Iterate over the absence records of the given employees.

        Pages through :meth:`search_gaps` until the API reports no more
        pages. One item is yielded per employee of a page, so an
        employee without absences yields an entry with an empty `gaps`
        list.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/search-gaps

        :param users: logins or ids of the employees, at most 100.
        :param from_: start of the search window. The current moment by
            default.
        :param to: end of the search window.
        :param per_page: number of employees per page (50 by default).
        """
        page = 1
        while True:
            result = await self.search_gaps(
                users,
                from_=from_,
                to=to,
                per_page=per_page,
                page=page,
            )
            if not result.user_gaps:
                return

            for user_gaps in result.user_gaps:
                yield user_gaps

            if not result.has_more:
                return

            page += 1

    async def delete_gap(self, gap_id: str) -> bool:
        """Delete one absence record.

        An unknown id is ignored by the API instead of failing.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/delete-gaps

        :param gap_id: id of the absence record to delete.
        :return: True on success.
        """
        return await self.delete_gaps([gap_id])

    async def delete_gaps(self, gap_ids: Sequence[str]) -> bool:
        """Delete several absence records at once.

        Unknown ids are ignored by the API instead of failing.

        Source:
        https://yandex.ru/support/tracker/ru/api/gaps/delete-gaps

        :param gap_ids: ids of the absence records to delete, at most
            100, each at most 128 characters long. They are sent as one
            comma-separated `gapIds` query parameter.
        :return: True on success.
        """
        if len(gap_ids) > MAX_GAPS_PER_REQUEST:
            msg = (
                f"At most {MAX_GAPS_PER_REQUEST} absence records can be "
                f"deleted at once, got {len(gap_ids)}."
            )
            raise ValueError(msg)

        await self._client.request(
            method="DELETE",
            uri="/gaps",
            params={"gapIds": ",".join(str(gap_id) for gap_id in gap_ids)},
        )
        return True
