name: "Publish"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Resolve version
        id: package-version
        run: echo "value=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')" >> $GITHUB_OUTPUT

      - name: Store version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')
          (echo '__version__ = "'$VERSION'"' && cat ./yatracker/__init__.py) > _version.py && mv _version.py ./yatracker/__init__.py
          cat './yatracker/__init__.py'

      - name: Build source distribution
        run: python -m build .

      - name: Try install wheel
        run: |
          pip install -U virtualenv
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/yatracker-*.whl
          venv/bin/python -c "import yatracker; print(yatracker.__version__)"

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/yatracker/${{ steps.package-version.outputs.value }}/
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
